/** 라우트 경로 상수 */
export const ROUTES = {
  DASHBOARD: '/',
  DASHBOARD_VEHICLES: '/dashboard/vehicles',
  DASHBOARD_PROGRESS: '/dashboard/progress',
  DASHBOARD_EVENTS: '/dashboard/events',
  ORDERS: '/orders',
  ORDER_DETAIL: '/orders/:id',
  STOCKS: '/warehouse/stocks',
  INBOUNDS: '/warehouse/inbounds',
  INBOUND_DETAIL: '/warehouse/inbounds/:id',
  WAREHOUSE_WORK: '/warehouse/work',
  LOADING: '/delivery/loading',
  DISPATCH: '/delivery/dispatch',
  DELIVERY_STATUS: '/delivery/status',
  DELIVERY_RESULT: '/delivery/result',
  RETURNS: '/returns',
  RETURN_DETAIL: '/returns/:id',
  SCHEDULE: '/schedule',
  AUDIT_LOGS: '/audit-logs',
  PRODUCTS: '/master/products',
  LOCATIONS: '/master/locations',
  LOCATIONS_3D: '/master/locations/3d',
  VEHICLES: '/master/fleet/vehicles',
  DRIVERS: '/master/fleet/drivers',
} as const;
